# Generated by Django 3.0.7 on 2021-06-04 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='email',
            new_name='nl_email',
        ),
    ]
