# Generated by Django 3.0.7 on 2021-08-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0002_auto_20210820_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='pic',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
