# Generated by Django 3.0.7 on 2021-08-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0004_auto_20210820_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
