# Generated by Django 3.0.7 on 2021-08-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0007_auto_20210823_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_message',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
