# Generated by Django 3.2 on 2021-12-11 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0011_auto_20211210_1608'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
